### ISSUE TITLE
Microsoft.Practices.ServiceLocation reference 

### ISSUE THREAD

**Issue by SimonCropp** [unitycontainer/unity#10]
I notice 4.0.0 has a ref on `Microsoft.Practices.ServiceLocation, Version=1.3.0.0`

should it have a nuget dependency on https://www.nuget.org/packages/CommonServiceLocator/ ?

**Comment by SimonCropp** [comment]
Actually i notice it does have a dependency but not for all versions 

https://github.com/unitycontainer/unity/blob/master/source/NuGet/Unity.nuspec#L16

for context i am getting an assembly load exception when trying to use 4.0 sating it cant load Microsoft.Practices.ServiceLocation

**Comment by pcibraro** [comment]
I will have to get that one from Microsoft. I don't have that code yet. Let me fix this issue in the meantime

**Comment by pcibraro** [comment]
Unit tests are passing, what's the scenario you are testing so I can repro the issue? Thanks

**Comment by SimonCropp** [comment]
1. create a 4.5 console app
 2. `PM> install-package unity`
 3. add this code `var types = typeof(IUnityContainer).Assembly.GetTypes();`

```
System.Reflection.ReflectionTypeLoadException was unhandled
  HResult=-2146232830
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
       at System.Reflection.Assembly.GetTypes()
       at ConsoleApplication1.Program.Main(String[] args) in C:\Code\ConsoleApplication1\ConsoleApplication1\Program.cs:line 14
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

with the loader exception being

```
{"Could not load file or assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. '
The system cannot find the file specified.":"Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
```

**Comment by SimonCropp** [comment]
your unit tests are probably passing since `Microsoft.Practices.ServiceLocation` is copied to the bin directory as part of the inferred references in the `Unity` project

**Comment by pcibraro** [comment]
I already asked P&p for the code of the service locator. I hope I can fix this asap. Thanks

El oct 3, 2015 1:38 AM, Simon Cropp <notifications@github.com> escribió:
your unit tests are probably passing since `Microsoft.Practices.ServiceLocation` is copied to the bin directory as part of the inferred references in the `Unity` project

---

**Comment by SimonCropp** [comment]
Sorry i am a little confused. Why cant u add a nuger dependency?

**Comment by eric-newton** [comment]
Wait wait wait.  I came here because I'm experiencing the same issue, due to Unity dependency on CommonServiceLocator 1.3.0 which when used in a .Net framework 4.5.2 build environment fails due to some System.Runtime,4.0.0.0 referencing issue. (google "teamcity system.runtime 4.0.0.0 referencing problem)

The problem is the dependency of Unity on CommonServiceLocator, which is failing to update their references for proper framework >4.0.0 support (something about needing proper signing I believe?)

Currently I just question why Unity needs CommonServiceLocator as a dependency at all... The proper operation here (until CommonServiceLocator is ACTUALLY part of BCL) is for using Reflection to determine if ServiceLocator.SetServiceLocator method is available.

Frankly, NodeJS and Javascript modules in general dont have these type of referencing problems, because the JS runtime is far more flexible at using types/methods when the signatures match up.

My suggestion is to "keep it runtime bound" but keep the actual runtime bindings minimal and not in regular code paths.   Use Reflection.Emit to tightly bind at runtime.  etc.

**Comment by eric-newton** [comment]
Hello?  We basically need CommonServiceLocator dependency removed, and possibly a new Nuget package with any bits that refer to ServiceLocator (like you do with Unity.Mvc/Unity.WebApi/etc)

Frankly this does not need a dependency to CommonServiceLocator because ServiceLocator itself is an anti-pattern itself... http://stackoverflow.com/a/22795888

**Comment by bigjoed** [comment]
Any movement on this issue as described by @eric-newton ? I too am experiencing the same issue when attempting to upgrade to framework 4.5.2

**Comment by arielszklarkiewicz** [comment]
Hi. What error are you exactly getting?

**Comment by DanBailiff** [comment]
Just ran into the same issue as eric-newton. Introducing CommonServiceLocator as a dependency is a no-go for my project.  If Unity needs this library, I'll have to do the painful thing and swap Unity for something else. Can we please get a version without this dependency?

**Comment by ENikS** [comment]
The ServiceLocation is removed into separate project
