### ISSUE TITLE
Split Unity package into separate NuGet packages

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/unity#241]
## Problem
Unity package contain Configuration and Interception packages as well as Container. When referenced by project it automatically links all these even if not used by the project.

## Solution
Starting with version 5.9.0 Unity package will only contain Unity.Abstractions and Unity.Container packages. All other packages will be available as individual NuGet packages. In other words Unity.nupkg:
- Unity.Abstractions
- Unity.Container

## Impact
Projects relaying on these packages removed from Unity will have to be updated with references to individually published packages.

**Comment by MatthewSteeples** [comment]
Is it worth making the Unity.nupkg a "meta-package" so that it just references Unity.Abstractions and Unity.Container as dependencies rather than being copies of them

**Comment by ENikS** [comment]
For corporate users it would be disastrous. I am afraid just by splitting these I will make many unhappy users.

**Comment by ENikS** [comment]
Done

**Comment by MatthewSteeples** [comment]
Hi, this is causing us some problems because we now need to choose whether we use the "all in one" package or manually install the sub-packages. Can I ask why you think it's a disaster for corporate users? Other packages (Humanizer for example) have a main meta-package

**Comment by ENikS** [comment]
Big companies with security departments have to go through onboarding process for these packages. Changing Unity to meta-package would require onboarding of Unity as well as all the packages it references. So it sort of defeats the whole purpose. 

Personally, I do not see any benefit is changing package to meta.

**Comment by MatthewSteeples** [comment]
It depends what the "on-boarding process" is. When I'm reviewing meta packages, it takes about 5 minutes to see that it's a meta one and realise that I'm moving on to its dependencies. There are no additional DLLs to verify, they're just organised differently. It would also mean that if you patch just one library, there's no need to release a new version of the others, so it's actually _less_ work for enterprises to do because they only need to audit the single file that's changed, rather than the whole package.

The problem we're seeing is that Unity.AspNet.WebApi and Unity.Mvc depend on Unity.Container. This means that we have 2 packages (Unity and Unity.Container) providing the same dlls. And until external dependencies start relying on Unity.Container, we'll need to keep both packages installed (which, I'm sure you can see, means that we're having to on-board Unity twice)

**Comment by MatthewSteeples** [comment]
Because the packages we're using will still depend on the two different options (one depending on Unity, one depending on Unity.Container). They're out of our control

**Comment by ENikS** [comment]
Unfortunately, I have to decline your suggestion. It will stay as it is for now.
