### ISSUE TITLE
Unity.ResolutionFailedException

### ISSUE THREAD

**Issue by klyse** [unitycontainer/unity#270]
### Description

Unity throws exception on resolve after update.

### To Reproduce

Update Unity to new version.

Unity version: **5.9.2**
Unity.Abstractions: **4.0.2**

Compile and run.

```C#
// init unity
IUnityContainer sp = new UnityContainer();

//initializing services
sp.RegisterSingleton<ILogger, Logger>();
sp.RegisterSingleton<IMessageHandler, MessageHandler>();
sp.RegisterSingleton<IStopwatchMonitor, StopwatchMonitor>();
sp.AddExtension(new Diagnostic());

var messageHandler = sp.Resolve<IMessageHandler>(); // this line throws an exception
```
![image](https://user-images.githubusercontent.com/10352866/51822040-53c34880-22db-11e9-9f6e-f2f3c6ef1d83.png)

**Additional context**

This happens only since the update 5.9.2 on all of my projects.

**Comment by TheMidgardWatcher** [comment]
Hi,

I want to add additional Unity.ResolutionFailedException since 5.9.2 version:
```Injection Factory must return valid object or throw an exception``` 

I'm trying to register factory in Web Application which returns something from Owin Context:
```container.RegisterFactory<IUser>((t, s, o) => HttpContext.Current.GetOwinContext().Get<IUsert>("User"), new HierarchicalLifetimeManager());```

This registration fails since I've updated to the latest Unity version. I've tried to throw exception if Owin returns null but there was no luck... What should i do to make factory work?

And one more ResolutionFailedExceprion is throwing  by Unity for standard MVC Interfaces:
```Unity.ResolutionFailedException: 'The current type, System.Web.Mvc.IControllerFactory, is an interface and cannot be constructed. Are you missing a type mapping?```

How to get rid of this?

**Comment by klyse** [comment]
> How to get rid of this?

I don't know if our issues are related. But what I know is that I reverted the update and stick to the old version until I understand whats going on here.

**Comment by ENikS** [comment]
@klyse It looks like Unsafe dependency is missing.  What platform are you running it on? 
I would suggest to link to `Unity.Container` package for now. I will add missing dependency to Unity package in next release.

@TheMidgardWatcher  Your issue is not related to this one. Please open separate issue and provide unit test so I could debug it.

**Comment by klyse** [comment]
@ENikS I run this on .net Core 2.2 and .net framework 4.7.2 (multiple projects have the same issue)
Adding Unity.Container has not solved this issue for me.

**Comment by ENikS** [comment]
It is starange, [Unity.Container](https://www.nuget.org/packages/Unity.Container/) clearly states missing dependency. 

Can you make a small repo with project do demo the bug?

**Comment by klyse** [comment]
@ENikS I created the repository **klyse/UnityTest** let me know if you find something.

The master branch fails, the workingVersion branch shows that it worked with the old version.

**Comment by klyse** [comment]
@ENikS any updates?

**Comment by klyse** [comment]
Hi,
just checked my example again:
looks like unit version:
Unity version: **5.9.5**
Unity.Abstractions: **4.0.3**
Solved my initial problem.
