### ISSUE TITLE
Unity 3.5.405 - Strong-named assembly

### ISSUE THREAD

**Issue by zezuni** [unitycontainer/unity#6]
In the latest release the Unity assemblies are no longer strong-named.
Will there be support for strong-named assemblies or is this an intentional change?

**Comment by pcibraro** [comment]
Do you have a requirement to have the assemblies strongly signed ?. This was an intentional change. Since the code was donated to us by Microsoft, we are not longer in possession of the original signing key. If you still need strong-named assemblies, we can review that but the signature will different as a new key will have to be used. Thanks

**Comment by zezuni** [comment]
I do have those requirements since we use Unity in all our products to handle dependency injection.
For us, there is no problem in changing the signature key.

We would be more than thankful if you could review this.

Thanks.

**Comment by pcibraro** [comment]
I just pushed a new version, which is signed.
